version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: attendance_db
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my_network
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: attendance_db

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
